### ISSUE TITLE
Throwing errors instead of console.error and not requiring a React installation for pure javascript environments

### ISSUE THREAD

**Issue by volovikariel** [harfy345/npm-true-false-condition#1]
Hello!

Just checked out the package and had some questions.

1. Have you considered throwing an error instead of just calling console.error?
By throwing errors, users will be able to explicitly handle errors, or the program will simply fail at runtime, which is what would normally happen with ternary operators. 
You could have InvalidCondition and InvalidParameters errors for example to differentiate the errors.

2. Have you considered allowing non-booleans? Truthiness in JavaScript does not stop at booleans!

3. Additionally, have you thought about how - if a user is using React, then they'll already have it installed. So maybe having it inside of package.json is not needed?
Instead, you could check if React is defined, this way, if they have React installed, it'll be initialized normally.
This way, you don't need to install all of React just to have a ternary operator inside of your pure-JavaScript application!

```js
let React;
try {
    React = require('react');
} catch (error) {
    React = false;
}

function true_then_else_then(condition, item1, item2) {
    // ...
    // Check if both parameters are React components
    if (React && React.isValidElement(item1) && React.isValidElement(item2)) {
        return condition ? item1 : item2; // Return React components
    }
    // ...
}
```

EDIT: Wrote this quite late at night. As I was in bed, I thought to myself, if this is a drop-in replacement for the ternary operator, why not just `return condition ? item1 : item2`?
I came to the conclusion that this seems to be a specialized kind of ternary expression, which ensures that you don't mix and match React components/functions, and it doesn't allow for "primitives" (e.g: condition ? "yay" : "nay").

More power to you

**Comment by harfy345** [comment]
Oh wow those are very interesting points, I am so thankful for those ideas, I was just so happy and excited to publish it and I didn't have time to improve it and optimize it but I will work on the for the next time. Thank you so much again for this beautiful comment :)

**Comment by harfy345** [comment]
> Hello!
> 
> Just checked out the package and had some questions.
> 
> 1. Have you considered throwing an error instead of just calling console.error?
>    By throwing errors, users will be able to explicitly handle errors, or the program will simply fail at runtime, which is what would normally happen with ternary operators.
>    You could have InvalidCondition and InvalidParameters errors for example to differentiate the errors.
> 2. Have you considered allowing non-booleans? Truthiness in JavaScript does not stop at booleans!
> 3. Additionally, have you thought about how - if a user is using React, then they'll already have it installed. So maybe having it inside of package.json is not needed?
>    Instead, you could check if React is defined, this way, if they have React installed, it'll be initialized normally.
>    This way, you don't need to install all of React just to have a ternary operator inside of your pure-JavaScript application!
> 
> ```js
> let React;
> try {
>     React = require('react');
> } catch (error) {
>     React = false;
> }
> 
> function true_then_else_then(condition, item1, item2) {
>     // ...
>     // Check if both parameters are React components
>     if (React && React.isValidElement(item1) && React.isValidElement(item2)) {
>         return condition ? item1 : item2; // Return React components
>     }
>     // ...
> }
> ```

Oh wow those are very interesting points, I am so thankful for those ideas, I was just so happy and excited to publish it and I didn't have time to improve it and optimize it but I will work on the for the next time. Thank you so much again for this beautiful comment :)
